### ISSUE TITLE
Great stuff!

### ISSUE THREAD

**Issue by fullofcaffeine** [pleclech/hacking-haxe#1]
Very interesting changes you've done there. Maybe someday this could be ported back to the main source code? :)

I was also thinking about changing Haxe in a way that it wouldn't always require a class, but would automatically stick code to a "Main" object (just like Ruby does), this would make Haxe good as a typed scripting language. I find that creating a class just for to have a main method kind of verbose. This would be a nice experiment too.

This together with a good (cross platform?) REPL would make for a very powerful combo, in my opinion.

What are your thoughts on that?

Even if those changes don't get ported back, they are here to prove that Haxe's syntax can and will eventually be improved, and to show people that hacking the compiler is actually a possibility. Inspiring stuff, keep up the great work.

**Comment by pleclech** [comment]
Thanks.
I don't think it will be ported back, too away from haxe philsophy ;) 
For the rest i will think about, for the moment i try to clean up the code and fix some bugs as i broke some part of the compiler

**Comment by fullofcaffeine** [comment]
Cool, thanks. Keep up the great work!

**Comment by pleclech** [comment]
thanks
