### ISSUE TITLE
singleton object

### ISSUE THREAD

**Issue by fponticelli** [pleclech/hacking-haxe#2]
It would be lovely to have something like the scala objects (they exists globally and they can implement interfaces and/or classes).

**Comment by pleclech** [comment]
I will think how hard it is to emulate it ;)
What will be you use of this ?
For the moment i'm cleaning an trying to fix (in branch hacking-haxe-reload) some part i broke into the compiler

**Comment by fponticelli** [comment]
In essence you give up on static members and embrace a unified world where everything is an instance. It is quite powerful but I understand it is quite distant from the Haxe way.

**Comment by pleclech** [comment]
Maybe this https://github.com/pleclech/hacking-haxe/commit/8016faed7cc0a0a568b4a770b2cedca58ced89b2 close the issue
